# Generated by Django 5.2.15 on 2026-07-07 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_name', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('storage_location', models.CharField(max_length=50)),
                ('dispensing_location', models.CharField(max_length=50)),
                ('lid_type', models.CharField(max_length=20)),
                ('storage_stock', models.IntegerField(default=0)),
                ('dispensing_stock', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dispensing.event')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispensing.medicine')),
            ],
        ),
    ]
