# Generated by Django 5.2.15 on 2026-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='status',
            field=models.CharField(choices=[('READY', 'READY'), ('REFILL_REQUIRED', 'REFILL_REQUIRED')], default='READY', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('REFILL_REQUIRED', 'REFILL_REQUIRED'), ('WAITING', 'WAITING'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE')], default='WAITING', max_length=20),
        ),
    ]
