# Generated by Django 5.2.15 on 2026-07-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing', '0002_eventitem_status_alter_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='min_stock',
        ),
    ]
