# Generated by Django 5.2.15 on 2026-07-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing', '0003_remove_medicine_min_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='dispensing_location',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='storage_location',
        ),
        migrations.AddField(
            model_name='medicine',
            name='dispensing_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dispensing_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dispensing_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_z',
            field=models.FloatField(default=0.0),
        ),
    ]
