# Generated by Django 5.2.15 on 2026-07-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing', '0004_remove_medicine_dispensing_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='drawer_rx',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drawer_ry',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drawer_rz',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drawer_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drawer_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drawer_z',
            field=models.FloatField(default=0.0),
        ),
    ]
