# Generated by Django 5.2.15 on 2026-07-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing', '0005_medicine_drawer_rx_medicine_drawer_ry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dispensing_rx',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dispensing_ry',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dispensing_rz',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_rx',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_ry',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_rz',
            field=models.FloatField(default=0.0),
        ),
    ]
