# Generated by Django 5.2.15 on 2026-07-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing', '0006_medicine_dispensing_rx_medicine_dispensing_ry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='bottle_tip_offset_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='bottle_tip_offset_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='bottle_tip_offset_z',
            field=models.FloatField(default=0.0),
        ),
    ]
